data_path: '/lambda_stor/homes/bhsu/gb_2024/my_gb_files/metric_learn/data/arxiv_emb_processed_multi.parquet'
num_samples: 50000
batch_size: 256
train_ratio: 0.8
val_ratio: 0.15
num_blocks: 5
input_size: 768
output_size: 768
block_pattern:
- 512
- 256
- 512
batch_norm: true
activation: ReLU
lr: 0.0001
optimizer_name: AdamW
optimizer:
  lr: 0.001
  weight_decay: 0.001
scheduler_name: CosineAnnealing
scheduler:
  T_max: 5
margin: 0.2
loss_name: NTXent
loss:
    temperature: 0.5
mining_name: None
accuracy_name: Standard
accuracy:
  include:
  - precision_at_1
  - mean_average_precision
  k: 1
